---

- name: add backports repository
  apt_repository: repo='deb http://httpredir.debian.org/debian jessie-backports main contrib non-free' state=present update_cache=yes 

- name: install nginx-full package
  apt: name=nginx-full state=latest default_release=jessie-backports

- name: create strong DH parameters
  shell: openssl dhparam -dsaparam -out /etc/nginx/dhparam.pem 4096
  args:
    creates: /etc/nginx/dhparam.pem
